// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://vtdcrhpzjcnjxfqmtukk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ0ZGNyaHB6amNuanhmcW10dWtrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI3NDc2NjcsImV4cCI6MjA4ODMyMzY2N30.L-p7d2vuOsalDLHJkGmQ_gLS3DDmEwj5KTSkZhNzgGs";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);